# Pydantic schemas for the Agent microservice
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class AgentRequest(BaseModel):
    query: str = Field(..., description="The query or task for the agent to execute")
    agent_name: str = Field(..., description="The name of the target agent (e.g., research, summarizer, memory)")
    conversation_id: Optional[str] = Field(None, description="The active conversation session ID")
    config: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Custom parameters for the agent runtime")

class AgentResponse(BaseModel):
    agent_name: str
    status: str
    response: str = Field(..., description="The final text answer generated by the agent")
    steps: List[str] = Field(default_factory=list, description="The execution trace list")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata and metrics")

class AgentStatus(BaseModel):
    job_id: str
    status: str = Field(..., description="One of: pending, running, completed, failed")
    current_step: Optional[str] = None
    started_at: float
    completed_at: Optional[float] = None
    errors: List[str] = Field(default_factory=list)
